publish_tf: true                       # wheter or not to publish the tf::transform (base->odom)
freq: 8.0                               # Execution frequency. See "Planar Odometry from a Radial Laser Scanner. A Range Flow-based Approach. ICRA'16"
init_pose_from_topic: ""                # (Odom topic) Leave empty to start at point (0,0)
verbose: true




